dist/Dockerfile.build/Dockerfile: Install protobuf-compiler
To make protoc available, so we can generate (and check freshness of)
cincinnati/src/plugins/interface.rs in CI, avoiding [1,2]:

  thread 'main' panicked at 'protoc: Custom { kind: NotFound, error: "failed to spawn `\"protoc\" \"--version\"`: No such file or directory (os error 2)" }', src/libcore/result.rs:1188:5

[1]: https://github.com/openshift/release/pull/6935#issuecomment-580955178
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6935/rehearse-6935-pull-ci-openshift-cincinnati-master-images/11#1:build-log.txt%3A420