Bump openssl-sys and openssl
Resolves:

```
warning: build/expando.c:4:24: error: pasting "RUST_VERSION_OPENSSL_" and "(" does not give a valid preprocessing token
warning:     4 | #define VERSION2(n, v) RUST_VERSION_##n##_##v
warning:       |                        ^~~~~~~~~~~~~
warning: build/expando.c:5:23: note: in expansion of macro 'VERSION2'
warning:     5 | #define VERSION(n, v) VERSION2(n, v)
warning:       |                       ^~~~~~~~
warning: build/expando.c:10:1: note: in expansion of macro 'VERSION'
warning:    10 | VERSION(OPENSSL, OPENSSL_VERSION_NUMBER)
warning:       | ^~~~~~~
error: failed to run custom build command for `openssl-sys v0.9.63`
```

From https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cincinnati/786/pull-ci-openshift-cincinnati-master-customrust-images/1653741007713341440#1:build-log.txt%3A3892-3900

I was inspecting that CI job and found out that bumping to CentOS Stream 9
contains a bump to OpenSSL 3.0.0 which needed special support in the
`openssl` package:

- https://bugzilla.redhat.com/show_bug.cgi?id=1948976
- https://github.com/sfackler/rust-openssl/pull/1264
- https://github.com/rust-lang/rust/pull/86529